//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Entities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AccountsDbEntities : DbContext
    {
        public AccountsDbEntities()
            : base("name=AccountsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AccountGroup> tbl_AccountGroup { get; set; }
        public virtual DbSet<tbl_AccountLedger> tbl_AccountLedger { get; set; }
        public virtual DbSet<tbl_AdditionalCost> tbl_AdditionalCost { get; set; }
        public virtual DbSet<tbl_AdvancePayment> tbl_AdvancePayment { get; set; }
        public virtual DbSet<tbl_Area> tbl_Area { get; set; }
        public virtual DbSet<tbl_BankReconciliation> tbl_BankReconciliation { get; set; }
        public virtual DbSet<tbl_BarcodeSettings> tbl_BarcodeSettings { get; set; }
        public virtual DbSet<tbl_Batch> tbl_Batch { get; set; }
        public virtual DbSet<tbl_Bom> tbl_Bom { get; set; }
        public virtual DbSet<tbl_BonusDeduction> tbl_BonusDeduction { get; set; }
        public virtual DbSet<tbl_Brand> tbl_Brand { get; set; }
        public virtual DbSet<tbl_BudgetDetails> tbl_BudgetDetails { get; set; }
        public virtual DbSet<tbl_BudgetMaster> tbl_BudgetMaster { get; set; }
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<tbl_CompanyPath> tbl_CompanyPath { get; set; }
        public virtual DbSet<tbl_ContraDetails> tbl_ContraDetails { get; set; }
        public virtual DbSet<tbl_ContraMaster> tbl_ContraMaster { get; set; }
        public virtual DbSet<tbl_Counter> tbl_Counter { get; set; }
        public virtual DbSet<tbl_CreditNoteDetails> tbl_CreditNoteDetails { get; set; }
        public virtual DbSet<tbl_CreditNoteMaster> tbl_CreditNoteMaster { get; set; }
        public virtual DbSet<tbl_Currency> tbl_Currency { get; set; }
        public virtual DbSet<tbl_DailyAttendanceDetails> tbl_DailyAttendanceDetails { get; set; }
        public virtual DbSet<tbl_DailyAttendanceMaster> tbl_DailyAttendanceMaster { get; set; }
        public virtual DbSet<tbl_DailySalaryVoucherDetails> tbl_DailySalaryVoucherDetails { get; set; }
        public virtual DbSet<tbl_DailySalaryVoucherMaster> tbl_DailySalaryVoucherMaster { get; set; }
        public virtual DbSet<tbl_DebitNoteDetails> tbl_DebitNoteDetails { get; set; }
        public virtual DbSet<tbl_DebitNoteMaster> tbl_DebitNoteMaster { get; set; }
        public virtual DbSet<tbl_DeliveryNoteDetails> tbl_DeliveryNoteDetails { get; set; }
        public virtual DbSet<tbl_DeliveryNoteMaster> tbl_DeliveryNoteMaster { get; set; }
        public virtual DbSet<tbl_Designation> tbl_Designation { get; set; }
        public virtual DbSet<tbl_Details> tbl_Details { get; set; }
        public virtual DbSet<tbl_DetailsCopy> tbl_DetailsCopy { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_ExchangeRate> tbl_ExchangeRate { get; set; }
        public virtual DbSet<tbl_Fields> tbl_Fields { get; set; }
        public virtual DbSet<tbl_FieldsCopy> tbl_FieldsCopy { get; set; }
        public virtual DbSet<tbl_FinancialYear> tbl_FinancialYear { get; set; }
        public virtual DbSet<tbl_Form> tbl_Form { get; set; }
        public virtual DbSet<tbl_FormCopy> tbl_FormCopy { get; set; }
        public virtual DbSet<tbl_Godown> tbl_Godown { get; set; }
        public virtual DbSet<tbl_Holiday> tbl_Holiday { get; set; }
        public virtual DbSet<tbl_JournalDetails> tbl_JournalDetails { get; set; }
        public virtual DbSet<tbl_JournalMaster> tbl_JournalMaster { get; set; }
        public virtual DbSet<tbl_LedgerPosting> tbl_LedgerPosting { get; set; }
        public virtual DbSet<tbl_Master> tbl_Master { get; set; }
        public virtual DbSet<tbl_MasterCopy> tbl_MasterCopy { get; set; }
        public virtual DbSet<tbl_MaterialReceiptDetails> tbl_MaterialReceiptDetails { get; set; }
        public virtual DbSet<tbl_MaterialReceiptMaster> tbl_MaterialReceiptMaster { get; set; }
        public virtual DbSet<tbl_ModelNo> tbl_ModelNo { get; set; }
        public virtual DbSet<tbl_MonthlySalary> tbl_MonthlySalary { get; set; }
        public virtual DbSet<tbl_MonthlySalaryDetails> tbl_MonthlySalaryDetails { get; set; }
        public virtual DbSet<tbl_PartyBalance> tbl_PartyBalance { get; set; }
        public virtual DbSet<tbl_PayHead> tbl_PayHead { get; set; }
        public virtual DbSet<tbl_PaymentDetails> tbl_PaymentDetails { get; set; }
        public virtual DbSet<tbl_PaymentMaster> tbl_PaymentMaster { get; set; }
        public virtual DbSet<tbl_PDCClearanceMaster> tbl_PDCClearanceMaster { get; set; }
        public virtual DbSet<tbl_PDCPayableMaster> tbl_PDCPayableMaster { get; set; }
        public virtual DbSet<tbl_PDCReceivableMaster> tbl_PDCReceivableMaster { get; set; }
        public virtual DbSet<tbl_PhysicalStockDetails> tbl_PhysicalStockDetails { get; set; }
        public virtual DbSet<tbl_PhysicalStockMaster> tbl_PhysicalStockMaster { get; set; }
        public virtual DbSet<tbl_PriceList> tbl_PriceList { get; set; }
        public virtual DbSet<tbl_PricingLevel> tbl_PricingLevel { get; set; }
        public virtual DbSet<tbl_Privilege> tbl_Privilege { get; set; }
        public virtual DbSet<tbl_Product> tbl_Product { get; set; }
        public virtual DbSet<tbl_ProductGroup> tbl_ProductGroup { get; set; }
        public virtual DbSet<tbl_PurchaseBillTax> tbl_PurchaseBillTax { get; set; }
        public virtual DbSet<tbl_PurchaseDetails> tbl_PurchaseDetails { get; set; }
        public virtual DbSet<tbl_PurchaseMaster> tbl_PurchaseMaster { get; set; }
        public virtual DbSet<tbl_PurchaseOrderDetails> tbl_PurchaseOrderDetails { get; set; }
        public virtual DbSet<tbl_PurchaseOrderMaster> tbl_PurchaseOrderMaster { get; set; }
        public virtual DbSet<tbl_PurchaseReturnBilltax> tbl_PurchaseReturnBilltax { get; set; }
        public virtual DbSet<tbl_PurchaseReturnDetails> tbl_PurchaseReturnDetails { get; set; }
        public virtual DbSet<tbl_PurchaseReturnMaster> tbl_PurchaseReturnMaster { get; set; }
        public virtual DbSet<tbl_QuickLaunchItems> tbl_QuickLaunchItems { get; set; }
        public virtual DbSet<tbl_QuickLaunchItemsToCopy> tbl_QuickLaunchItemsToCopy { get; set; }
        public virtual DbSet<tbl_Rack> tbl_Rack { get; set; }
        public virtual DbSet<tbl_ReceiptDetails> tbl_ReceiptDetails { get; set; }
        public virtual DbSet<tbl_ReceiptMaster> tbl_ReceiptMaster { get; set; }
        public virtual DbSet<tbl_RejectionInDetails> tbl_RejectionInDetails { get; set; }
        public virtual DbSet<tbl_RejectionInMaster> tbl_RejectionInMaster { get; set; }
        public virtual DbSet<tbl_RejectionOutDetails> tbl_RejectionOutDetails { get; set; }
        public virtual DbSet<tbl_RejectionOutMaster> tbl_RejectionOutMaster { get; set; }
        public virtual DbSet<tbl_Reminder> tbl_Reminder { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_Route> tbl_Route { get; set; }
        public virtual DbSet<tbl_SalaryPackage> tbl_SalaryPackage { get; set; }
        public virtual DbSet<tbl_SalaryPackageDetails> tbl_SalaryPackageDetails { get; set; }
        public virtual DbSet<tbl_SalaryVoucherDetails> tbl_SalaryVoucherDetails { get; set; }
        public virtual DbSet<tbl_SalaryVoucherMaster> tbl_SalaryVoucherMaster { get; set; }
        public virtual DbSet<tbl_SalesBillTax> tbl_SalesBillTax { get; set; }
        public virtual DbSet<tbl_SalesDetails> tbl_SalesDetails { get; set; }
        public virtual DbSet<tbl_SalesMaster> tbl_SalesMaster { get; set; }
        public virtual DbSet<tbl_SalesOrderDetails> tbl_SalesOrderDetails { get; set; }
        public virtual DbSet<tbl_SalesOrderMaster> tbl_SalesOrderMaster { get; set; }
        public virtual DbSet<tbl_SalesQuotationDetails> tbl_SalesQuotationDetails { get; set; }
        public virtual DbSet<tbl_SalesQuotationMaster> tbl_SalesQuotationMaster { get; set; }
        public virtual DbSet<tbl_SalesReturnBillTax> tbl_SalesReturnBillTax { get; set; }
        public virtual DbSet<tbl_SalesReturnDetails> tbl_SalesReturnDetails { get; set; }
        public virtual DbSet<tbl_SalesReturnMaster> tbl_SalesReturnMaster { get; set; }
        public virtual DbSet<tbl_Service> tbl_Service { get; set; }
        public virtual DbSet<tbl_ServiceCategory> tbl_ServiceCategory { get; set; }
        public virtual DbSet<tbl_ServiceDetails> tbl_ServiceDetails { get; set; }
        public virtual DbSet<tbl_ServiceMaster> tbl_ServiceMaster { get; set; }
        public virtual DbSet<tbl_Settings> tbl_Settings { get; set; }
        public virtual DbSet<tbl_SettingsToCopy> tbl_SettingsToCopy { get; set; }
        public virtual DbSet<tbl_Size> tbl_Size { get; set; }
        public virtual DbSet<tbl_StandardRate> tbl_StandardRate { get; set; }
        public virtual DbSet<tbl_StockJournalDetails> tbl_StockJournalDetails { get; set; }
        public virtual DbSet<tbl_StockJournalMaster> tbl_StockJournalMaster { get; set; }
        public virtual DbSet<tbl_StockPosting> tbl_StockPosting { get; set; }
        public virtual DbSet<tbl_SuffixPrefix> tbl_SuffixPrefix { get; set; }
        public virtual DbSet<tbl_Tax> tbl_Tax { get; set; }
        public virtual DbSet<tbl_TaxDetails> tbl_TaxDetails { get; set; }
        public virtual DbSet<tbl_Unit> tbl_Unit { get; set; }
        public virtual DbSet<tbl_UnitConvertion> tbl_UnitConvertion { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_VoucherType> tbl_VoucherType { get; set; }
        public virtual DbSet<tbl_VoucherTypeTax> tbl_VoucherTypeTax { get; set; }
        public virtual DbSet<tbl_VoucherTypeToCopy> tbl_VoucherTypeToCopy { get; set; }
        public virtual DbSet<tbl_CurrencyToCopy> tbl_CurrencyToCopy { get; set; }
        public virtual DbSet<CashInOutFlow1> CashInOutFlow1 { get; set; }
        public virtual DbSet<ViewCashBank> ViewCashBanks { get; set; }
        public virtual DbSet<vwStockQuery> vwStockQueries { get; set; }
    
        [DbFunction("AccountsDbEntities", "AccountGroupHierarchy")]
        public virtual IQueryable<AccountGroupHierarchy_Result> AccountGroupHierarchy(Nullable<decimal> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AccountGroupHierarchy_Result>("[AccountsDbEntities].[AccountGroupHierarchy](@groupId)", groupIdParameter);
        }
    
        [DbFunction("AccountsDbEntities", "AccountLedgerGetGroupUnderFunction")]
        public virtual IQueryable<AccountLedgerGetGroupUnderFunction_Result> AccountLedgerGetGroupUnderFunction(string accountGroupId)
        {
            var accountGroupIdParameter = accountGroupId != null ?
                new ObjectParameter("accountGroupId", accountGroupId) :
                new ObjectParameter("accountGroupId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AccountLedgerGetGroupUnderFunction_Result>("[AccountsDbEntities].[AccountLedgerGetGroupUnderFunction](@accountGroupId)", accountGroupIdParameter);
        }
    
        [DbFunction("AccountsDbEntities", "MIS_CustomerTable")]
        public virtual IQueryable<MIS_CustomerTable_Result> MIS_CustomerTable(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MIS_CustomerTable_Result>("[AccountsDbEntities].[MIS_CustomerTable](@fromDate, @toDate)", fromDateParameter, toDateParameter);
        }
    
        [DbFunction("AccountsDbEntities", "MIS_DateTimeTable")]
        public virtual IQueryable<MIS_DateTimeTable_Result> MIS_DateTimeTable(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MIS_DateTimeTable_Result>("[AccountsDbEntities].[MIS_DateTimeTable](@fromDate, @toDate)", fromDateParameter, toDateParameter);
        }
    
        [DbFunction("AccountsDbEntities", "MIS_MonthTable")]
        public virtual IQueryable<MIS_MonthTable_Result> MIS_MonthTable(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MIS_MonthTable_Result>("[AccountsDbEntities].[MIS_MonthTable](@fromDate, @toDate)", fromDateParameter, toDateParameter);
        }
    
        [DbFunction("AccountsDbEntities", "MIS_SupplierTable")]
        public virtual IQueryable<MIS_SupplierTable_Result> MIS_SupplierTable(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MIS_SupplierTable_Result>("[AccountsDbEntities].[MIS_SupplierTable](@fromDate, @toDate)", fromDateParameter, toDateParameter);
        }
    
        [DbFunction("AccountsDbEntities", "ProductGroupHierarchy")]
        public virtual IQueryable<ProductGroupHierarchy_Result> ProductGroupHierarchy(Nullable<decimal> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ProductGroupHierarchy_Result>("[AccountsDbEntities].[ProductGroupHierarchy](@groupId)", groupIdParameter);
        }
    }
}
